#本地环境
spring:
  redis:
    database: 3
    host: localhost
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://127.0.0.1/wechat?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 8
      max-idle: 100
      test-while-idle: true
      time-between-eviction-runs-millis: 600000
      min-evictable-idle-time-millis: 600000
      validation-query: select 1
      num-tests-per-eviction-run: 10

